{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "OK-Clinic-API",
    "description" : "API for OK Vet Clinic",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/xavieruniversityaten/OK-Clinic-API/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "http://OK-Clinic-API"
  } ],
  "tags" : [ {
    "name" : "Pet",
    "description" : "Operations related to pets"
  }, {
    "name" : "Owner",
    "description" : "Operations related to pet owners"
  }, {
    "name" : "Appointment",
    "description" : "Operations related to appointments"
  }, {
    "name" : "MedicalRecords",
    "description" : "Operations related to medical records"
  } ],
  "paths" : {
    "/pet" : {
      "get" : {
        "tags" : [ "Pet" ],
        "summary" : "Get all registered pets",
        "description" : "Get all registered pets",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by pet id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of pets"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "post" : {
        "tags" : [ "Pet" ],
        "summary" : "Add a new pet",
        "description" : "Add a new pet",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Pet"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Pet created successfully"
          },
          "400" : {
            "description" : "Bad request - invalid input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/pet/{id}" : {
      "get" : {
        "tags" : [ "Pet" ],
        "summary" : "Get pet details by ID",
        "description" : "Get details of a specific pet by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Pet details found"
          }
        }
      },
      "put" : {
        "tags" : [ "Pet" ],
        "summary" : "Update pet information",
        "description" : "Update the pet's info (petName, petSpecies, petAge)",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Pet"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Pet updated successfully"
          },
          "400" : {
            "description" : "Bad request - invalid update"
          },
          "404" : {
            "description" : "Pet not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/owner" : {
      "get" : {
        "tags" : [ "Owner" ],
        "summary" : "Get list of all owners",
        "description" : "Get list of all owners",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by owner id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of owners"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "post" : {
        "tags" : [ "Owner" ],
        "summary" : "Register a new pet owner",
        "description" : "Register a new pet owner",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Owner"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Owner registered successfully"
          },
          "400" : {
            "description" : "Bad request - invalid input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/owner/{id}" : {
      "get" : {
        "tags" : [ "Owner" ],
        "summary" : "Fetch details of a specific owner",
        "description" : "Get details of an owner by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Owner details found"
          },
          "404" : {
            "description" : "Owner not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/appointment" : {
      "get" : {
        "tags" : [ "Appointment" ],
        "summary" : "Retrieve all appointments",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by appointment id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of appointments",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Appointment"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "post" : {
        "tags" : [ "Appointment" ],
        "summary" : "Book a new appointment",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Appointment"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Appointment booked successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Appointment"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request - invalid input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/appointment/{id}" : {
      "get" : {
        "tags" : [ "Appointment" ],
        "summary" : "Get details of a specific appointment",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Appointment details found",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Appointment"
                }
              }
            }
          },
          "404" : {
            "description" : "Appointment not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "put" : {
        "tags" : [ "Appointment" ],
        "summary" : "Update or reschedule an appointment",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/appointment_id_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Appointment updated successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Appointment"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request - invalid update"
          },
          "404" : {
            "description" : "Appointment not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "delete" : {
        "tags" : [ "Appointment" ],
        "summary" : "Cancel an appointment",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "Appointment cancelled successfully"
          },
          "404" : {
            "description" : "Appointment not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/records" : {
      "get" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "List all medical records",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by record id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of medical records",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/MedicalRecord"
                  }
                }
              }
            }
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "post" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "Add a new medical record for a pet",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/MedicalRecord"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Medical record added successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MedicalRecord"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request - invalid input"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    },
    "/records/{id}" : {
      "get" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "View medical record by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Medical record details found",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MedicalRecord"
                }
              }
            }
          },
          "404" : {
            "description" : "Medical record not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      },
      "put" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "Update a medical record",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/records_id_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Medical record updated successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/MedicalRecord"
                }
              }
            }
          },
          "400" : {
            "description" : "Bad request - invalid update"
          },
          "404" : {
            "description" : "Medical record not found"
          },
          "500" : {
            "description" : "Internal server error"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Pet" : {
        "required" : [ "ownerID", "petAge", "petName", "petSpecies" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "unique identifier for the Pet"
          },
          "petName" : {
            "type" : "string"
          },
          "petSpecies" : {
            "type" : "string"
          },
          "petAge" : {
            "type" : "integer"
          },
          "ownerID" : {
            "type" : "integer",
            "description" : "Foreign Key- links to an owner's id property"
          },
          "owner" : {
            "$ref" : "#/components/schemas/Owner"
          }
        }
      },
      "Owner" : {
        "required" : [ "ownerAddress", "ownerEmail", "ownerFullName", "ownerNum" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "Unique identifier for the Owner"
          },
          "ownerFullName" : {
            "type" : "string"
          },
          "ownerEmail" : {
            "type" : "string"
          },
          "ownerNum" : {
            "type" : "integer",
            "description" : "Phone number of owner"
          },
          "ownerAddress" : {
            "type" : "string"
          }
        }
      },
      "Appointment" : {
        "required" : [ "date", "ownerID", "petID", "staffID", "timeSlot" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "Unique identifier for the appointment"
          },
          "date" : {
            "type" : "string",
            "description" : "Appointment date (YYYY-MM-DD)",
            "format" : "date"
          },
          "timeSlot" : {
            "type" : "string",
            "description" : "Time slot for appointment (e.g., '9:00 AM')"
          },
          "ownerID" : {
            "type" : "integer",
            "description" : "Foreign Key - links to Owner by ID"
          },
          "petID" : {
            "type" : "integer",
            "description" : "Foreign Key - links to Pet by ID"
          },
          "staffID" : {
            "type" : "integer",
            "description" : "Foreign Key - links to Staff by id"
          },
          "owner" : {
            "$ref" : "#/components/schemas/Owner"
          }
        }
      },
      "MedicalRecord" : {
        "required" : [ "dateUponRecord", "diagnosis", "petName" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "description" : "Unique identifier for medical records"
          },
          "petName" : {
            "type" : "string",
            "description" : "Foreign Key - links to Pet since they are the patients here"
          },
          "diagnosis" : {
            "type" : "string",
            "description" : "Diagnosis for pet patient"
          },
          "dateUponRecord" : {
            "type" : "string",
            "description" : "Date of the medical record (YYYY-MM-DD)",
            "format" : "date"
          }
        }
      },
      "appointment_id_body" : {
        "type" : "object",
        "properties" : {
          "date" : {
            "type" : "string",
            "format" : "date"
          },
          "timeSlot" : {
            "type" : "string"
          },
          "petID" : {
            "type" : "integer"
          },
          "staffID" : {
            "type" : "integer"
          }
        }
      },
      "records_id_body" : {
        "type" : "object",
        "properties" : {
          "diagnosis" : {
            "type" : "string"
          },
          "dateUponRecord" : {
            "type" : "string",
            "format" : "date"
          }
        }
      }
    }
  }
}