{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "OK Clinic API",
    "description" : "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!\nYou can now help us improve the API whether it's by making changes to the definition itself or to the code.\nThat way, with time, we can improve the API in general, and expose some of the new features in OAS3.\n\nSome useful links:\n- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)\n- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)",
    "termsOfService" : "https://swagger.io/terms/",
    "contact" : {
      "email" : "apiteam@swagger.io"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.0.0"
  },
  "externalDocs" : {
    "description" : "Find out more about Swagger",
    "url" : "https://swagger.io"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "tags" : [ {
    "name" : "pet",
    "description" : "Everything about your Pets",
    "externalDocs" : {
      "description" : "Find out more",
      "url" : "https://swagger.io"
    }
  }, {
    "name" : "store",
    "description" : "Access to Petstore orders",
    "externalDocs" : {
      "description" : "Find out more about our store",
      "url" : "https://swagger.io"
    }
  }, {
    "name" : "user",
    "description" : "Operations about user"
  } ],
  "paths" : {
    "/pet" : {
      "put" : {
        "tags" : [ "pet" ],
        "summary" : "Update an existing pet.",
        "description" : "Update an existing pet by Id.",
        "operationId" : "updatePet",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid ID supplied",
            "content" : { }
          },
          "404" : {
            "description" : "Pet not found",
            "content" : { }
          },
          "422" : {
            "description" : "Validation exception",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      },
      "post" : {
        "tags" : [ "pet" ],
        "summary" : "Add a new pet to the store.",
        "description" : "Add a new pet to the store.",
        "operationId" : "addPet",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid input",
            "content" : { }
          },
          "422" : {
            "description" : "Validation exception",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      }
    },
    "/pet/findByStatus" : {
      "get" : {
        "tags" : [ "pet" ],
        "summary" : "Finds Pets by status.",
        "description" : "Multiple status values can be provided with comma separated strings.",
        "operationId" : "findPetsByStatus",
        "parameters" : [ {
          "name" : "status",
          "in" : "query",
          "description" : "Status values that need to be considered for filter",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid status value",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      }
    },
    "/pet/findByTags" : {
      "get" : {
        "tags" : [ "pet" ],
        "summary" : "Finds Pets by tags.",
        "description" : "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
        "operationId" : "findPetsByTags",
        "parameters" : [ {
          "name" : "tags",
          "in" : "query",
          "description" : "Tags to filter by",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid tag value",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      }
    },
    "/pet/{petId}" : {
      "get" : {
        "tags" : [ "pet" ],
        "summary" : "Find pet by ID.",
        "description" : "Returns a single pet.",
        "operationId" : "getPetById",
        "parameters" : [ {
          "name" : "petId",
          "in" : "path",
          "description" : "ID of pet to return",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid ID supplied",
            "content" : { }
          },
          "404" : {
            "description" : "Pet not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "api_key" : [ ]
        }, {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      },
      "post" : {
        "tags" : [ "pet" ],
        "summary" : "Updates a pet in the store with form data.",
        "description" : "Updates a pet resource based on the form data.",
        "operationId" : "updatePetWithForm",
        "parameters" : [ {
          "name" : "petId",
          "in" : "path",
          "description" : "ID of pet that needs to be updated",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        }, {
          "name" : "name",
          "in" : "query",
          "description" : "Name of pet that needs to be updated",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        }, {
          "name" : "status",
          "in" : "query",
          "description" : "Status of pet that needs to be updated",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid input",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      },
      "delete" : {
        "tags" : [ "pet" ],
        "summary" : "Deletes a pet.",
        "description" : "Delete a pet.",
        "operationId" : "deletePet",
        "parameters" : [ {
          "name" : "api_key",
          "in" : "header",
          "required" : false,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        }, {
          "name" : "petId",
          "in" : "path",
          "description" : "Pet id to delete",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Pet deleted",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid pet value",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      }
    },
    "/pet/{petId}/uploadImage" : {
      "post" : {
        "tags" : [ "pet" ],
        "summary" : "Uploads an image.",
        "description" : "Upload image of the pet.",
        "operationId" : "uploadFile",
        "parameters" : [ {
          "name" : "petId",
          "in" : "path",
          "description" : "ID of pet to update",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        }, {
          "name" : "additionalMetadata",
          "in" : "query",
          "description" : "Additional Metadata",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "No file uploaded",
            "content" : { }
          },
          "404" : {
            "description" : "Pet not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "petstore_auth" : [ "write:pets", "read:pets" ]
        } ]
      }
    },
    "/store/inventory" : {
      "get" : {
        "tags" : [ "store" ],
        "summary" : "Returns pet inventories by status.",
        "description" : "Returns a map of status codes to quantities.",
        "operationId" : "getInventory",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        },
        "security" : [ {
          "api_key" : [ ]
        } ]
      }
    },
    "/store/order" : {
      "post" : {
        "tags" : [ "store" ],
        "summary" : "Place an order for a pet.",
        "description" : "Place a new order in the store.",
        "operationId" : "placeOrder",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid input",
            "content" : { }
          },
          "422" : {
            "description" : "Validation exception",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    },
    "/store/order/{orderId}" : {
      "get" : {
        "tags" : [ "store" ],
        "summary" : "Find purchase order by ID.",
        "description" : "For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.",
        "operationId" : "getOrderById",
        "parameters" : [ {
          "name" : "orderId",
          "in" : "path",
          "description" : "ID of order that needs to be fetched",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid ID supplied",
            "content" : { }
          },
          "404" : {
            "description" : "Order not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      },
      "delete" : {
        "tags" : [ "store" ],
        "summary" : "Delete purchase order by identifier.",
        "description" : "For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors.",
        "operationId" : "deleteOrder",
        "parameters" : [ {
          "name" : "orderId",
          "in" : "path",
          "description" : "ID of the order that needs to be deleted",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Order deleted",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid ID supplied",
            "content" : { }
          },
          "404" : {
            "description" : "Order not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    },
    "/user" : {
      "post" : {
        "tags" : [ "user" ],
        "summary" : "Create user.",
        "description" : "This can only be done by the logged in user.",
        "operationId" : "createUser",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    },
    "/user/createWithList" : {
      "post" : {
        "tags" : [ "user" ],
        "summary" : "Creates list of users with given input array.",
        "description" : "Creates list of users with given input array.",
        "operationId" : "createUsersWithListInput",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    },
    "/user/login" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "Logs user into the system.",
        "description" : "Log into the system.",
        "operationId" : "loginUser",
        "parameters" : [ {
          "name" : "username",
          "in" : "query",
          "description" : "The user name for login",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        }, {
          "name" : "password",
          "in" : "query",
          "description" : "The password for login in clear text",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "headers" : {
              "X-Rate-Limit" : {
                "description" : "calls per hour allowed by the user",
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "object"
                }
              },
              "X-Expires-After" : {
                "description" : "date in UTC when token expires",
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "object"
                }
              }
            },
            "content" : { }
          },
          "400" : {
            "description" : "Invalid username/password supplied",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    },
    "/user/logout" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "Logs out current logged in user session.",
        "description" : "Log user out of the system.",
        "operationId" : "logoutUser",
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    },
    "/user/{username}" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "Get user by user name.",
        "description" : "Get user detail based on username.",
        "operationId" : "getUserByName",
        "parameters" : [ {
          "name" : "username",
          "in" : "path",
          "description" : "The name that needs to be fetched. Use user1 for testing",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid username supplied",
            "content" : { }
          },
          "404" : {
            "description" : "User not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      },
      "put" : {
        "tags" : [ "user" ],
        "summary" : "Update user resource.",
        "description" : "This can only be done by the logged in user.",
        "operationId" : "updateUser",
        "parameters" : [ {
          "name" : "username",
          "in" : "path",
          "description" : "The name that needs to be updated",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request",
            "content" : { }
          },
          "404" : {
            "description" : "User not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      },
      "delete" : {
        "tags" : [ "user" ],
        "summary" : "Delete user resource.",
        "description" : "This can only be done by the logged in user.",
        "operationId" : "deleteUser",
        "parameters" : [ {
          "name" : "username",
          "in" : "path",
          "description" : "The name that needs to be deleted",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "User deleted",
            "content" : { }
          },
          "400" : {
            "description" : "Invalid username supplied",
            "content" : { }
          },
          "404" : {
            "description" : "User not found",
            "content" : { }
          },
          "default" : {
            "description" : "Unexpected error",
            "content" : { }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : { }
  },
  "x-original-swagger-version" : null
}