{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "OK-Clinic-API",
    "description" : "API for OK Vet Clinic. Submitted by Almonte, Dosdos, and Lumacad in compliance of the requirements of ITCC 14 B.",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "tags" : [ {
    "name" : "Pets",
    "description" : "Operations related to pets"
  }, {
    "name" : "Owners",
    "description" : "Operations related to pet owners"
  } ],
  "paths" : {
    "/pets" : {
      "get" : {
        "tags" : [ "Pets" ],
        "summary" : "Get all registered pets",
        "description" : "Get all registered pets",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by pet id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of pets",
            "content" : { }
          }
        }
      },
      "post" : {
        "tags" : [ "Pets" ],
        "summary" : "Add a new pet",
        "description" : "Add a new pet",
        "responses" : {
          "201" : {
            "description" : "Pet created successfully",
            "content" : { }
          }
        }
      }
    },
    "/pets/{id}" : {
      "get" : {
        "tags" : [ "Pets" ],
        "summary" : "Get pet details by ID",
        "description" : "Get details of a specific pet by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Pet details found",
            "content" : { }
          }
        }
      },
      "put" : {
        "tags" : [ "Pets" ],
        "summary" : "Update pet information",
        "description" : "Update the pet's info (petName, petSpecies, petAge)",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Pet updated successfully",
            "content" : { }
          }
        }
      }
    },
    "/owners" : {
      "get" : {
        "tags" : [ "Owners" ],
        "summary" : "Get list of all owners",
        "description" : "Get list of all owners",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by owner id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of owners",
            "content" : { }
          }
        }
      },
      "post" : {
        "tags" : [ "Owners" ],
        "summary" : "Register a new pet owner",
        "description" : "Register a new pet owner",
        "responses" : {
          "201" : {
            "description" : "Owner registered successfully",
            "content" : { }
          }
        }
      }
    },
    "/owners/{id}" : {
      "get" : {
        "tags" : [ "Owners" ],
        "summary" : "Fetch details of a specific owner",
        "description" : "Get details of an owner by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Owner details found",
            "content" : { }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : { }
  },
  "x-original-swagger-version" : null
}