{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "OK-Clinic-API",
    "description" : "API for OK Vet Clinic. Submitted by Almonte, Dosdos, and Lumacad in compliance of the requirements of ITCC 14 B.",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "tags" : [ {
    "name" : "Pet",
    "description" : "Operations related to pets"
  }, {
    "name" : "Owner",
    "description" : "Operations related to pet owners"
  }, {
    "name" : "Appointment",
    "description" : "Operations related to appointments"
  }, {
    "name" : "MedicalRecords",
    "description" : "Operations related to medical records"
  } ],
  "paths" : {
    "/pet" : {
      "get" : {
        "tags" : [ "Pet" ],
        "summary" : "Get all registered pets",
        "description" : "Get all registered pets",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by pet id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of pets",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "post" : {
        "tags" : [ "Pet" ],
        "summary" : "Add a new pet",
        "description" : "Add a new pet",
        "responses" : {
          "201" : {
            "description" : "Pet created successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid input",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/pet/{id}" : {
      "get" : {
        "tags" : [ "Pet" ],
        "summary" : "Get pet details by ID",
        "description" : "Get details of a specific pet by its ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Pet details found",
            "content" : { }
          }
        }
      },
      "put" : {
        "tags" : [ "Pet" ],
        "summary" : "Update pet information",
        "description" : "Update the pet's info (petName, petSpecies, petAge)",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Pet updated successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid update",
            "content" : { }
          },
          "404" : {
            "description" : "Pet not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/owner" : {
      "get" : {
        "tags" : [ "Owner" ],
        "summary" : "Get list of all owners",
        "description" : "Get list of all owners",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by owner id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of owners",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "post" : {
        "tags" : [ "Owner" ],
        "summary" : "Register a new pet owner",
        "description" : "Register a new pet owner",
        "responses" : {
          "201" : {
            "description" : "Owner registered successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid input",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/owner/{id}" : {
      "get" : {
        "tags" : [ "Owner" ],
        "summary" : "Fetch details of a specific owner",
        "description" : "Get details of an owner by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Owner details found",
            "content" : { }
          },
          "404" : {
            "description" : "Owner not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/appointment" : {
      "get" : {
        "tags" : [ "Appointment" ],
        "summary" : "Retrieve all appointments",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by appointment id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of appointments",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "post" : {
        "tags" : [ "Appointment" ],
        "summary" : "Book a new appointment",
        "responses" : {
          "201" : {
            "description" : "Appointment booked successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid input",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/appointment/{id}" : {
      "get" : {
        "tags" : [ "Appointment" ],
        "summary" : "Get details of a specific appointment",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Appointment details found",
            "content" : { }
          },
          "404" : {
            "description" : "Appointment not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "put" : {
        "tags" : [ "Appointment" ],
        "summary" : "Update or reschedule an appointment",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Appointment updated successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid update",
            "content" : { }
          },
          "404" : {
            "description" : "Appointment not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "delete" : {
        "tags" : [ "Appointment" ],
        "summary" : "Cancel an appointment",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "204" : {
            "description" : "Appointment cancelled successfully",
            "content" : { }
          },
          "404" : {
            "description" : "Appointment not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/records" : {
      "get" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "List all medical records",
        "parameters" : [ {
          "name" : "id",
          "in" : "query",
          "description" : "(Optional) Filter by record id",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "List of medical records",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "post" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "Add a new medical record for a pet",
        "responses" : {
          "201" : {
            "description" : "Medical record added successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid input",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    },
    "/records/{id}" : {
      "get" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "View medical record by ID",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Medical record details found",
            "content" : { }
          },
          "404" : {
            "description" : "Medical record not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      },
      "put" : {
        "tags" : [ "MedicalRecords" ],
        "summary" : "Update a medical record",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : { }
        } ],
        "responses" : {
          "200" : {
            "description" : "Medical record updated successfully",
            "content" : { }
          },
          "400" : {
            "description" : "Bad request - invalid update",
            "content" : { }
          },
          "404" : {
            "description" : "Medical record not found",
            "content" : { }
          },
          "500" : {
            "description" : "Internal server error",
            "content" : { }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : { }
  },
  "x-original-swagger-version" : null
}